/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.Connect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akbar
 */
public class EmployeeList extends javax.swing.JInternalFrame {

    /**
     * Creates new form CustomerViwe
     */
    DefaultTableModel dtm;
    
    public EmployeeList() {
        initComponents();
           dtm = (DefaultTableModel) empTab.getModel();
                getValues();

    }
    Invoice iobj;
    
    public EmployeeList(Invoice obj) {
        initComponents();
           dtm = (DefaultTableModel) empTab.getModel();
                getValues();
                iobj=obj;
    }

   SalesReturn srobj;
    public EmployeeList(SalesReturn obj) {
        initComponents();
           dtm = (DefaultTableModel) empTab.getModel();
                getValues();
                srobj=obj;

    }
//    EditCustomer ecobj;
    
//    CustomerList(EditCustomer obj){
//    initComponents();
//    dtm = (DefaultTableModel) cusTbl.getModel();
//    getValues();
//    ecobj = obj ;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        empTab = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchNameTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        searchPosTxt = new javax.swing.JTextField();
        refreshBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        empTab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        empTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Position", "Phone no", "NIC", "Adrress"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empTabMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(empTab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(17, 153, 148));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Employee List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Search By Name");

        searchNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameTxtActionPerformed(evt);
            }
        });
        searchNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchNameTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchNameTxtKeyTyped(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Position");

        searchPosTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPosTxtActionPerformed(evt);
            }
        });
        searchPosTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchPosTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchPosTxtKeyTyped(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(searchNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchPosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBtn)
                        .addComponent(jLabel2)
                        .addComponent(searchNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(searchPosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("*  To edit a employee double click on respective row");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        AddNewEmployee a = new AddNewEmployee();
        a.setVisible(true);
        getParent().add(a);
        a.toFront();
    }//GEN-LAST:event_addBtnActionPerformed

    private void empTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empTabMouseClicked
        if (evt.getClickCount() == 2) {
            int row = empTab.getSelectedRow();
            int empno = (int) empTab.getValueAt(row,0);
            String empname =  empTab.getValueAt(row,1).toString();
            String emppos =  empTab.getValueAt(row,2).toString();
            String emptel =  empTab.getValueAt(row,3).toString();
            String empnic =  empTab.getValueAt(row,4).toString();
            String empaddress =  empTab.getValueAt(row,5).toString();
            
//           if(iobj != null){
//              iobj.setCustomer(cusno);
//           }
//           if(ecobj != null){
//              ecobj.setCustomer1(cusno,cusname, cusaddress, custel,cusnic );
//           }
            if(iobj != null){
                          
              iobj.SetEmployee(empno,empname );
              this.dispose();
              
           }else if(srobj != null){
//            srobj.setCustomer(empno,empname);
            this.dispose();
           }
            
            else{
                EditEmployee a = new EditEmployee();
                a.setVisible(true);
                getParent().add(a);
                a.toFront();
                a.setinfo(empno , empname, emppos, emptel, empnic,empaddress);
            
            }
            
           
//
                
        }
    }//GEN-LAST:event_empTabMouseClicked

    private void searchNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameTxtActionPerformed


    }//GEN-LAST:event_searchNameTxtActionPerformed

    private void searchNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchNameTxtKeyTyped
    }//GEN-LAST:event_searchNameTxtKeyTyped

    private void searchNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchNameTxtKeyReleased
        // TODO add your handling code here:
        Connect c = new Connect(); 
        String query = "SELECT employee_id, employee_name, phn, position,em_add, em_nic FROM employee WHERE employee_name like '%"+searchNameTxt.getText()+"%' "   ;
        ResultSet reset = c.getQuery(query);
        dtm.setRowCount(0);
        try {
            while(reset.next()){
                int empno = reset.getInt("employee_id");
                String empname = reset.getString("employee_name");
                String emppos = reset.getString("position");
                String empphn = reset.getString("phn");
                String empnic = reset.getString("em_nic");
                String empadd = reset.getString("em_add");
                
                dtm.addRow(new Object[]{empno, empname,emppos, empphn, empnic, empadd });
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchNameTxtKeyReleased

    private void searchPosTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPosTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPosTxtActionPerformed

    private void searchPosTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPosTxtKeyReleased
        // TODO add your handling code here:
        Connect c = new Connect(); 
        String query = "SELECT employee_id, employee_name, phn, position,em_add, em_nic FROM employee WHERE position like '%"+searchPosTxt.getText()+"%' "   ;
        ResultSet reset = c.getQuery(query);
        dtm.setRowCount(0);

        try {
            while(reset.next()){
                int empno = reset.getInt("employee_id");
                String empname = reset.getString("employee_name");
                String emppos = reset.getString("position");
                String empphn = reset.getString("phn");
                String empnic = reset.getString("em_nic");
                String empadd = reset.getString("em_add");
                
                dtm.addRow(new Object[]{empno, empname,emppos, empphn, empnic, empadd });
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchPosTxtKeyReleased

    private void searchPosTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPosTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPosTxtKeyTyped

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        Connect c = new Connect(); 
        String query = "SELECT employee_id, employee_name, phn, position,em_add, em_nic FROM employee"  ;
        ResultSet reset = c.getQuery(query);
        try {
            while(reset.next()){
                int empno = reset.getInt("employee_id");
                String empname = reset.getString("employee_name");
                String emppos = reset.getString("position");
                String empphn = reset.getString("phn");
                String empnic = reset.getString("em_nic");
                String empadd = reset.getString("em_add");
                
                dtm.addRow(new Object[]{empno, empname,emppos, empphn, empnic, empadd });
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        searchNameTxt.setText("");
        searchPosTxt.setText("");
    }//GEN-LAST:event_refreshBtnActionPerformed
public void getValues(){
    
        Connect c = new Connect(); 
        String query = "SELECT employee_id, employee_name, phn, position,em_add, em_nic FROM employee"  ;
        ResultSet reset = c.getQuery(query);
        try {
            while(reset.next()){
                int empno = reset.getInt("employee_id");
                String empname = reset.getString("employee_name");
                String emppos = reset.getString("position");
                String empphn = reset.getString("phn");
                String empnic = reset.getString("em_nic");
                String empadd = reset.getString("em_add");
                
                dtm.addRow(new Object[]{empno, empname,emppos, empphn, empnic, empadd });
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
        }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable empTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField searchNameTxt;
    private javax.swing.JTextField searchPosTxt;
    // End of variables declaration//GEN-END:variables
}
