/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.Connect;
import java.awt.event.KeyEvent;
//import database.Report;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Hasini
 */
public class Grn extends javax.swing.JInternalFrame {

    
    private DefaultTableModel dtm;
    
    public Grn() {
        initComponents();        
        dtm = (DefaultTableModel) invtable.getModel();

        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat df1 = new SimpleDateFormat("hh:mm:ss");
        Date dobj=new Date();

        dateTxt.setText(df.format(dobj));
        timeTxt.setText(df1.format(dobj));
        grnid();
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ordernoTxt = new javax.swing.JTextField();
        supidTxt = new javax.swing.JTextField();
        supnameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        timeTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        supinnoTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        paybackDC = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        poTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        itemNoTxt = new javax.swing.JTextField();
        netTotalTxt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        itemIDTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        unitpTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        totalTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        qtyTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        invtable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        disc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(17, 153, 148));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("good receive note");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 40));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Date :");

        dateTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("GRN No:");

        ordernoTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ordernoTxt.setText("1");
        ordernoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordernoTxtActionPerformed(evt);
            }
        });

        supidTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        supidTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supidTxtMouseClicked(evt);
            }
        });
        supidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supidTxtActionPerformed(evt);
            }
        });

        supnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supnameTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Supplier ID");

        jLabel3.setText("Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Time :");

        timeTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        timeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTxtActionPerformed(evt);
            }
        });

        jLabel11.setText("Supplier invoice no");

        jLabel14.setText("Supplier invoice date");

        jLabel15.setText("PaybackDate");

        jLabel19.setText("po no");

        poTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(15, 15, 15)
                        .addComponent(poTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ordernoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(supidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(supnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(21, 21, 21)
                        .addComponent(supinnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel15)
                        .addGap(38, 38, 38)
                        .addComponent(paybackDC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(poTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordernoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(supnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(paybackDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(supinnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1040, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Net Amount");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("No of items");

        itemNoTxt.setEditable(false);
        itemNoTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemNoTxt.setToolTipText("");
        itemNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoTxtActionPerformed(evt);
            }
        });

        netTotalTxt.setEditable(false);
        netTotalTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netTotalTxt.setText("0.00");
        netTotalTxt.setToolTipText("");
        netTotalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netTotalTxtActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(netTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(itemNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 340, 390));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 129, 105, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Item no:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 301, 107, -1));

        itemIDTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemIDTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemIDTxtMouseClicked(evt);
            }
        });
        itemIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIDTxtActionPerformed(evt);
            }
        });
        itemIDTxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                itemIDTxtPropertyChange(evt);
            }
        });
        jPanel1.add(itemIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 321, 94, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Item Name:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 301, 98, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Unit Price:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 301, 91, 18));

        unitpTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unitpTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpTxtActionPerformed(evt);
            }
        });
        jPanel1.add(unitpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 321, 94, -1));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 351, 170, -1));

        removeBtn.setText("REMOVE");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 351, 200, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Total");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 301, 110, -1));

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 321, 94, -1));

        totalTxt.setEditable(false);
        totalTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTxtActionPerformed(evt);
            }
        });
        jPanel1.add(totalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 321, 80, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Quantity");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 301, 110, -1));

        qtyTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qtyTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyTxtFocusLost(evt);
            }
        });
        qtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTxtActionPerformed(evt);
            }
        });
        qtyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyTxtKeyTyped(evt);
            }
        });
        jPanel1.add(qtyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 321, 105, -1));

        invtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Qty", "Unit Price", "Total", "discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(invtable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 610, 280));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 351, 200, -1));

        disc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discMouseClicked(evt);
            }
        });
        disc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                discKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discKeyReleased(evt);
            }
        });
        jPanel1.add(disc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 321, 90, -1));

        jLabel16.setText("Discount per item :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 301, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 660, 390));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

        if(itemNoTxt.equals("0")){
            JOptionPane.showMessageDialog(this,"Please Add Items");
        }
        else{
          String supID = supidTxt.getText().trim();
          String SupInNo = supinnoTxt.getText().trim();
          
          java.sql.Date sqldate = new java.sql.Date(jDateChooser1.getDate().getTime());
          DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
          String supInDate = df.format(sqldate);
          
          java.sql.Date sqldate2 = new java.sql.Date(paybackDC.getDate().getTime());
          DateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
          String PaybkDate = df2.format(sqldate2);
          
            Connect c = new Connect();
            String query = "INSERT INTO grn (supplier_supplier_id, grn_date,supplier_invoice_no,supplier_invoice_date,payback_date) VALUES ("
            
            + supID + ","
            + "CURDATE()" + "," 
            + SupInNo + ","
            +  "'" + supInDate +"'"+ ","  
            +  "'" + PaybkDate +"'"       
            + ")";
            int genid =c.setQuery(query,"");
           

            int i;
            for (i = 0; i < invtable.getRowCount(); i++) {
                String tabID = invtable.getValueAt(i, 0).toString();
                String tabQty = invtable.getValueAt(i, 2).toString();
                String dicss = invtable.getValueAt(i, 5).toString();

                String query2 = "INSERT INTO grn_has_item ( grn_grnid, item_item_code, quantity,discount )VALUES ("

                + genid  + ","
                + tabID  + ","
                + tabQty  + ","
                + dicss
                + ")";
                c.setQuery(query2,"");
            }

            JOptionPane.showMessageDialog(this,"GRN Added");
        }
        
                supidTxt.setText("");
            int in=Integer.parseInt(ordernoTxt.getText().toString());
            
                    ordernoTxt.setText(Integer.toString(in+1));          
                    netTotalTxt.setText(""+0.00);
                    itemNoTxt.setText(""+0);
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void qtyTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTxtKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTxtKeyPressed

    private void qtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTxtActionPerformed
//        String qty = qtyTxt.getText();
//        String unitp = unitpTxt.getText();
//        double qtyD = Double.parseDouble(qty);
//        double unitpD = Double.parseDouble(unitp);
//        double total = (qtyD * unitpD);
//
//        totalTxt.setText(""+total);        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTxtActionPerformed

    private void qtyTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTxtFocusLost

    private void totalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String id = itemIDTxt.getText();
        String name = nameTxt.getText();
        String qty = qtyTxt.getText();
        String unitp = unitpTxt.getText();
        
        String discount=disc.getText();
        if (disc.getText().equals("")){
            discount="0";
        }
       
        double qtyD = Double.parseDouble(qty);
        double unitpD = Double.parseDouble(unitp);
        double total = qtyD * unitpD;

        int i;
        boolean found = false;
        for (i = 0; i < invtable.getRowCount(); i++) {
            String tabID = invtable.getValueAt(i, 0).toString();
            if (id.equals(tabID)) {
                found = true;
                break;
            }
        }
        if (found) {
            double oldQty = Double.parseDouble(invtable.getValueAt(i, 2).toString());
            double newQty = oldQty + qtyD;
            invtable.setValueAt("" + newQty, i, 2);
            
            double newTotal = (newQty * unitpD);
            invtable.setValueAt("" + newTotal, i, 4);
        } else {
            dtm.addRow(new Object[]{id, name, qty, unitp, total,discount});
        }

        try {
            double prevTotal = Double.parseDouble(netTotalTxt.getText());
            netTotalTxt.setText("" + (prevTotal + total));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Total Filed is empty");
        }
      
        
        itemIDTxt.setText("");
        nameTxt.setText("");
        qtyTxt.setText("");
        unitpTxt.setText("");
        totalTxt.setText("");
        disc.setText("");

        int itemNo = invtable.getRowCount();
        itemNoTxt.setText(""+itemNo);
        if(itemNoTxt.equals("0")){
            JOptionPane.showMessageDialog(this,"Please Add Items");
        }
        else{

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void unitpTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpTxtActionPerformed

    private void itemIDTxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_itemIDTxtPropertyChange

    }//GEN-LAST:event_itemIDTxtPropertyChange

    private void itemIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIDTxtActionPerformed

    }//GEN-LAST:event_itemIDTxtActionPerformed

    private void itemIDTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemIDTxtMouseClicked
        ItemViwe a = new ItemViwe(this);
        //        DashBoard.panel.add(a);
        a.setVisible(true);
        getParent().add(a);
        a.toFront();

    }//GEN-LAST:event_itemIDTxtMouseClicked

    private void dateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtActionPerformed

    private void ordernoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordernoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordernoTxtActionPerformed

    private void supidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supidTxtActionPerformed

    private void supidTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supidTxtMouseClicked
                SupplierList a = new SupplierList(this);
                a.setVisible(true);
                getParent().add(a);
                a.toFront();
    }//GEN-LAST:event_supidTxtMouseClicked

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBtnActionPerformed

    private void supnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supnameTxtActionPerformed

    private void netTotalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netTotalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netTotalTxtActionPerformed

    private void itemNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNoTxtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        supidTxt.setText("");
        ordernoTxt.setText("");
        netTotalTxt.setText(""+0.00);
        itemNoTxt.setText(""+0);
        
        dtm.setRowCount(0);
        itemIDTxt.setText("");
        nameTxt.setText("");
        qtyTxt.setText("");
        unitpTxt.setText("");
        totalTxt.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void timeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        
//          
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void discMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_discMouseClicked

    private void qtyTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTxtKeyTyped

    private void qtyTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTxtKeyReleased
        // TODO add your handling code here:
        String unitp = unitpTxt.getText();
        String qty = qtyTxt.getText();
        
            if (qty.equals("")){ // if not this gives error of null string
            
            }else {
                double qtyD = Double.parseDouble(qty);// to get total
                double unitpD = Double.parseDouble(unitp);
                double totalText = (qtyD * unitpD);
                totalTxt.setText(""+totalText);
            }     
             
            if (evt.getKeyCode()== KeyEvent.VK_ENTER){ // to enter data to table
                String id = itemIDTxt.getText();
                String name = nameTxt.getText();

                String discount=disc.getText();
                if (disc.getText().equals("")){
                    discount="0";
                }

                double qtyD = Double.parseDouble(qty);
                double unitpD = Double.parseDouble(unitp);
                double total = qtyD * unitpD;

                int i;
                boolean found = false;
                for (i = 0; i < invtable.getRowCount(); i++) {
                    String tabID = invtable.getValueAt(i, 0).toString();
                    if (id.equals(tabID)) {
                        found = true;
                        break;
                    }
                }
                if (found) {
                    double oldQty = Double.parseDouble(invtable.getValueAt(i, 2).toString());
                    double newQty = oldQty + qtyD;
                    invtable.setValueAt("" + newQty, i, 2);

                    double newTotal = (newQty * unitpD);
                    invtable.setValueAt("" + newTotal, i, 4);
                } else {
                    dtm.addRow(new Object[]{id, name, qty, unitp, total,discount});
                }

                try {
                    double prevTotal = Double.parseDouble(netTotalTxt.getText());
                    netTotalTxt.setText("" + (prevTotal + total));
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null, "Total Filed is empty");
                }
      
        
                itemIDTxt.setText("");
                nameTxt.setText("");
                qtyTxt.setText("");
                unitpTxt.setText("");
                totalTxt.setText("");


                int itemNo = invtable.getRowCount();
                itemNoTxt.setText(""+itemNo);
                if(itemNoTxt.equals("0")){
                    JOptionPane.showMessageDialog(this,"Please Add Items");
                }
                
                
//                if(evt.getKeyCode()== KeyEvent.VK_LEFT){
//                    System.out.println("dfdf");
//                    disc.requestFocusInWindow();
//
//        }
            }
                
    }//GEN-LAST:event_qtyTxtKeyReleased

    private void poTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poTxtMouseClicked
        // TODO add your handling code here:
        ViewPurchaseOrder vpo = new ViewPurchaseOrder(this);
        vpo.setVisible(true);
        getParent().add(vpo);
        vpo.toFront();
                
    }//GEN-LAST:event_poTxtMouseClicked

    private void discKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){ // to enter data to table
                String unitp = unitpTxt.getText();
                String qty = qtyTxt.getText();
                String id = itemIDTxt.getText();
                String name = nameTxt.getText();

                String discount=disc.getText();
                if (disc.getText().equals("")){
                    discount="0";
                }

                double qtyD = Double.parseDouble(qty);
                double unitpD = Double.parseDouble(unitp);
                double total = qtyD * unitpD;

                int i;
                boolean found = false;
                for (i = 0; i < invtable.getRowCount(); i++) {
                    String tabID = invtable.getValueAt(i, 0).toString();
                    if (id.equals(tabID)) {
                        found = true;
                        break;
                    }
                }
                if (found) {
                    double oldQty = Double.parseDouble(invtable.getValueAt(i, 2).toString());
                    double newQty = oldQty + qtyD;
                    invtable.setValueAt("" + newQty, i, 2);

                    double newTotal = (newQty * unitpD);
                    invtable.setValueAt("" + newTotal, i, 4);
                } else {
                    dtm.addRow(new Object[]{id, name, qty, unitp, total,discount});
                }

                try {
                    double prevTotal = Double.parseDouble(netTotalTxt.getText());
                    netTotalTxt.setText("" + (prevTotal + total));
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null, "Total Filed is empty");
                }
      
        
                itemIDTxt.setText("");
                nameTxt.setText("");
                qtyTxt.setText("");
                unitpTxt.setText("");
                totalTxt.setText("");


                int itemNo = invtable.getRowCount();
                itemNoTxt.setText(""+itemNo);
                if(itemNoTxt.equals("0")){
                    JOptionPane.showMessageDialog(this,"Please Add Items");
                }
                
                 if(evt.getKeyCode()== KeyEvent.VK_LEFT){
                    System.out.println("dfdf");

                    disc.requestFocusInWindow();

                    

        }
            }
    }//GEN-LAST:event_discKeyReleased

    private void discKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_LEFT){
                    System.out.println("dfdf");
//                    disc.requestFocusInWindow();

        }
    }//GEN-LAST:event_discKeyPressed
    void setItem(int itemno,String itemname){

        int ino = itemno;
        String iname = itemname;
        
        itemIDTxt.setText(""+ino);
        nameTxt.setText(iname);
        
        Connect c = new Connect();
        
        String query3 = "SELECT buying_price FROM stock_has_item WHERE item_item_code like '%"+ino+"%'" ;
        ResultSet reset3 = c.getQuery(query3);
        
        try {
            while(reset3.next()){
            
            int bpricee = reset3.getInt("buying_price");
            
            String bprice = Integer.toString(bpricee);

            unitpTxt.setText(bprice);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItemViwe.class.getName()).log(Level.SEVERE, null, ex);
        } 
                         qtyTxt.requestFocusInWindow();
// TODO add your handling code here:
    }   
        void setSupplier(int supid,String supname){
            int id = supid;
            String name= supname;
            supidTxt.setText(""+id);
            supnameTxt.setText(name);
        }
        
        void setPurchaseOrder (int POrderno, String POdate  ,String POSupId, String POItemCode, String POqty){
           
           String sid=POSupId;
           supidTxt.setText(sid);
           int Ordern=POrderno;
           poTxt.setText(""+Ordern);
           
           Connect c = new Connect();
        
            
             String query1="SELECT purchase_order.purchase_order_id"
                     + "purchase_order_has_item.item_item_code, purchase_order_has_item.quantity, "
                    
                    + "FROM purchase_order "
                    + " INNER JOIN  purchase_order_has_item"
//                    + "ON purchase_order_has_item.item_item_code = item.item_code) "
                    + "ON purchase_order_has_item.purchase_order_purchase_order_id = purchase_order.purchase_order_id "
                   +"WHERE purchase_order.purchase_order_id= "+Ordern+"  ";
       
                   
                    
//            String query1="SELECT purchase_order_has_item.item_item_code, purchase_order_has_item.quantity, "
//                    
//                    + "purchase_order.purchase_order_id "
//                    + "FROM purchase_order_has_item"
//                    + " INNER JOIN purchase_order "
////                    + "ON purchase_order_has_item.item_item_code = item.item_code) "
//                    + "ON purchase_order_has_item.purchase_order_purchase_order_id = purchase_order.purchase_order_id "
//                   +"WHERE purchase_order.purchase_order_id= "+Ordern+"  ";

            
            ResultSet reset = c.getQuery(query1);
            dtm.setRowCount(0);
            try {
                while(reset.next()){

                
//                String itemname = reset.getString("item_name");
                int itemid = reset.getInt("item_item_code");
                int itemqty = reset.getInt("quantity");


                dtm.addRow(new Object[]{ itemid,itemqty });
                }
            } catch (SQLException ex) {
                Logger.getLogger(ViewPurchaseOrder.class.getName()).log(Level.SEVERE, null, ex);
            }     
            
//            String query3 = "SELECT buying_price FROM stock_has_item WHERE item_item_code like '%"+Ordern+"%'" ;
//        ResultSet reset3 = c.getQuery(query3);
//        
//        try {
//            while(reset3.next()){
//            
//            int bpricee = reset3.getInt("buying_price");
//            
////            String bprice = Integer.toString(bpricee);
////
////            unitpTxt.setText(bprice);
//            
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(ItemViwe.class.getName()).log(Level.SEVERE, null, ex);
//        } 
//                         qtyTxt.requestFocusInWindow();
           
        }
        
        void grnid(){
        Connect c = new Connect();
        
                
        String query3 = "SELECT grnid FROM grn ORDER BY grnid DESC LIMIT 1" ;
        ResultSet reset3 = c.getQuery(query3);
        
        try {
            while(reset3.next()){
            
                int id = reset3.getInt("grnid");
                System.out.println(id);
                         String ids= Integer.toString((id+1));
            
                            ordernoTxt.setText(ids);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Invoice.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
     
        
       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField disc;
    private javax.swing.JTable invtable;
    private javax.swing.JTextField itemIDTxt;
    private javax.swing.JTextField itemNoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField netTotalTxt;
    private javax.swing.JTextField ordernoTxt;
    private com.toedter.calendar.JDateChooser paybackDC;
    private javax.swing.JTextField poTxt;
    private javax.swing.JTextField qtyTxt;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField supidTxt;
    private javax.swing.JTextField supinnoTxt;
    private javax.swing.JTextField supnameTxt;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JTextField unitpTxt;
    // End of variables declaration//GEN-END:variables
}
