/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.Connect;
import java.awt.Color;
import java.awt.Panel;
import java.awt.event.KeyEvent;
//import database.Report;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Hasini
 */
public class Invoice extends javax.swing.JInternalFrame {

    /**
     * Creates new form Invoice1
     */
    private DefaultTableModel dtm;
    
    public Invoice() {
        initComponents();
        Invoiceno();
        dtm = (DefaultTableModel) invtable.getModel();

               
        DateFormat df = new SimpleDateFormat("yy-MM-dd");
        DateFormat df1 = new SimpleDateFormat("hh:mm:ss");
        Date dobj=new Date();

        dateTxt.setText(df.format(dobj));
        timeTxt.setText(df1.format(dobj));
 
    }
    
    int cc;
    
    String banks;
    String dates;
    int chequeid;
    
    String ccardtype;
    String ccardno;
    String cbank;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        itemIDTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        barTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        unitpTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        discountTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invtable = new javax.swing.JTable();
        clearTxt = new javax.swing.JButton();
        qtyTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        invoicenoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cusidTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        timeTxt = new javax.swing.JTextField();
        empTxt = new javax.swing.JTextField();
        cusNameTxt = new javax.swing.JTextField();
        cashNameTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        paidTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        discTotalTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        balanceTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        subTotalTxt = new javax.swing.JTextField();
        NumberOfItemsTxt = new javax.swing.JTextField();
        netTotalTxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setIconifiable(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Item no:");

        itemIDTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemIDTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemIDTxtFocusGained(evt);
            }
        });
        itemIDTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemIDTxtMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemIDTxtMouseClicked(evt);
            }
        });
        itemIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIDTxtActionPerformed(evt);
            }
        });
        itemIDTxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                itemIDTxtPropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Bar Code:");

        barTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        barTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barTxtActionPerformed(evt);
            }
        });
        barTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barTxtKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Item Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Unit Price:");

        unitpTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unitpTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpTxtActionPerformed(evt);
            }
        });

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("REMOVE");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Total");

        discountTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        discountTxt.setText("0.00");
        discountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTxtActionPerformed(evt);
            }
        });

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameTxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nameTxtPropertyChange(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Discount");

        totalTxt.setEditable(false);
        totalTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTxtActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Quantity");

        invtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Qty", "Unit Price", "Total", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(invtable);

        clearTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearTxt.setText("Clear");
        clearTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTxtActionPerformed(evt);
            }
        });

        qtyTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qtyTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyTxtFocusLost(evt);
            }
        });
        qtyTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyTxtMouseClicked(evt);
            }
        });
        qtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTxtActionPerformed(evt);
            }
        });
        qtyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(barTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(itemIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(qtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(unitpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(discountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(clearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel4)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn)
                    .addComponent(removeBtn)
                    .addComponent(clearTxt)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 640, 440));

        jPanel3.setBackground(new java.awt.Color(17, 153, 148));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Invoice");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(584, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 40));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Date :");

        dateTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Invoice No:");

        invoicenoTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        invoicenoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicenoTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Customer ID");

        cusidTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cusidTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cusidTxtMouseClicked(evt);
            }
        });
        cusidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusidTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Cashier");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Time :");

        empTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoicenoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cusidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cusidTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(empTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cashNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoicenoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1070, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Net Amount");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("No of items");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Paid");
        jLabel21.setMaximumSize(new java.awt.Dimension(53, 17));

        paidTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paidTxt.setText("0.00");
        paidTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paidTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paidTxtFocusLost(evt);
            }
        });
        paidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidTxtActionPerformed(evt);
            }
        });
        paidTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidTxtKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Discount");

        discTotalTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        discTotalTxt.setText("0.00");
        discTotalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discTotalTxtActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Balance");

        balanceTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        balanceTxt.setText("0.00");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Total Amount");

        subTotalTxt.setEditable(false);
        subTotalTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subTotalTxt.setText("0.00");
        subTotalTxt.setToolTipText("");
        subTotalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalTxtActionPerformed(evt);
            }
        });

        NumberOfItemsTxt.setEditable(false);
        NumberOfItemsTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumberOfItemsTxt.setToolTipText("");
        NumberOfItemsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfItemsTxtActionPerformed(evt);
            }
        });

        netTotalTxt.setEditable(false);
        netTotalTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netTotalTxt.setText("0.00");
        netTotalTxt.setToolTipText("");
        netTotalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netTotalTxtActionPerformed(evt);
            }
        });

        jButton2.setText("Cheque");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Credit card");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        saveBtn.setText("Save & print the receipt");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(discTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(balanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(paidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumberOfItemsTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(netTotalTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberOfItemsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTotalTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 370, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cusidTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusidTxtMouseClicked
        CustomerList a = new CustomerList(this);
        a.setVisible(true);
        getParent().add(a);
        a.toFront();
        
    }//GEN-LAST:event_cusidTxtMouseClicked
    private void invoicenoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicenoTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_invoicenoTxtActionPerformed

    private void dateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtActionPerformed

    private void unitpTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String id = itemIDTxt.getText();
        String name = nameTxt.getText();
        String qty = qtyTxt.getText();
        String unitp = unitpTxt.getText();
        String discount = discountTxt.getText();
        String totdis = discTotalTxt.getText();
        
        
        
        double qtyD = Double.parseDouble(qty);
        double unitpD = Double.parseDouble(unitp);
        double disD = Double.parseDouble(discount);
        double total = qtyD * unitpD;
        double finaltotal = (qtyD * unitpD)-(qtyD * disD);

        
        int i;
        boolean found = false;
        for (i = 0; i < invtable.getRowCount(); i++) {
            String tabID = invtable.getValueAt(i, 0).toString();
            if (id.equals(tabID)) {
                found = true;
                break;
            }
        }
        if (found) {
            double oldQty = Double.parseDouble(invtable.getValueAt(i, 2).toString());
            double newQty = oldQty + qtyD;
            invtable.setValueAt("" + newQty, i, 2);
            
//            double oldtotal = Double.parseDouble(invtable.getValueAt(i, 4).toString());
            double newTotal = (newQty * unitpD)-(newQty * disD);
            invtable.setValueAt("" + newTotal, i, 4);
            
        } else {
            dtm.addRow(new Object[]{id, name, qty, unitp, finaltotal, discount});
        }
        
        try {
            double prevTotal = Double.parseDouble(netTotalTxt.getText());
            netTotalTxt.setText("" + (prevTotal + total));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Total Filed is empty");
        }
        try {
            double prevDiscount = Double.parseDouble(discTotalTxt.getText());
            double disc = Double.parseDouble(discount);
                       
            double totaldisc = prevDiscount+ (disc*qtyD);
                                    
            discTotalTxt.setText("" +  totaldisc);
            
            String nettot = netTotalTxt.getText();
            double netTot = Double.parseDouble(nettot);
            double subTot = netTot-totaldisc;
            subTotalTxt.setText(""+subTot);


        } catch (NumberFormatException nfe) {
        }
        
//        String nettot = netTotalTxt.getText();
//        
//        double disTot = Double.parseDouble(totdis);
//                System.out.println(disTot);
//
//        double netTot = Double.parseDouble(nettot);
//                        System.out.println(netTot);
//
//        double subTot = netTot-disTot;
//        System.out.println(subTot);
//        subTotalTxt.setText(""+subTot);
        
        itemIDTxt.setText("");
        nameTxt.setText("");
        qtyTxt.setText("");
        unitpTxt.setText("");
        totalTxt.setText("");
        discountTxt.setText(""+0.00);
        barTxt.setText("");
       
        int itemNo = invtable.getRowCount();
        NumberOfItemsTxt.setText(""+itemNo);
        if(NumberOfItemsTxt.equals("0")){
            JOptionPane.showMessageDialog(this,"Please Add Items");
        }
        else{

        }   

        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void discountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTxtActionPerformed

    private void paidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidTxtActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_paidTxtActionPerformed

    private void clearTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTxtActionPerformed
        cusidTxt.setText("");
       
        netTotalTxt.setText(""+0.00);
        NumberOfItemsTxt.setText(""+0);
        discTotalTxt.setText(""+0.00);
        subTotalTxt.setText(""+0.00);
        paidTxt.setText(""+0.00);
        balanceTxt.setText(""+0.00);
        dtm.setRowCount(0);
        itemIDTxt.setText("");
        nameTxt.setText("");
        qtyTxt.setText("");
        unitpTxt.setText("");
        totalTxt.setText("");
        discountTxt.setText(""+0.00);
        barTxt.setText(""); 
        dtm.setRowCount(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearTxtActionPerformed

    private void totalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTxtActionPerformed

    private void cusidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusidTxtActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

        
        
        if( cusidTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please fill customer field");
        }
        
        else if( empTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please fill employee field");
        }
        
        else if( NumberOfItemsTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please add items");
        }
        
        else{

//            String cusID = cusidTxt.getText().trim();
//            String netTotal = netTotalTxt.getText().trim();
//            String discount = discTotalTxt.getText().trim();
//            String subTotal = subTotalTxt.getText().trim();  
//            String Invoiceno = invoicenoTxt.getText().trim();
            String empid = empTxt.getText().trim();
            String cusid = cusidTxt.getText().trim();


            Connect c = new Connect();
            String query = "INSERT INTO invoice (date, time, employee_employee_id,customer_id) VALUES ("
                    + "CURDATE()" + ","
                    + "CURTIME()" + ","
                    + empid+ ","
                    + cusid
                    + ")";
            int genid =c.setQuery(query,"");
       
        
            int i;
                for (i = 0; i < invtable.getRowCount(); i++) {
                    String tabID = invtable.getValueAt(i, 0).toString();
                    String tabQty = invtable.getValueAt(i, 2).toString();
                    String tabUnitPrice = invtable.getValueAt(i, 3).toString();
                    String tabDis = invtable.getValueAt(i, 5).toString();
                
                    
            String query2 = "INSERT INTO invoice_has_item ( invoice_invoice_id, item_item_code, quantity, unit_price, discount )VALUES ("
            
                + genid  + ","
                + tabID  + ","        
                +  tabQty  + ","
                +  tabUnitPrice  + ","        
                +  tabDis 
                + ")";
            c.setQuery(query2,"");
            
            String query3 = "UPDATE stock_has_item SET"
                    + " quantity = quantity - " + "'" + tabQty + "'"
                    + "WHERE item_item_code =" + tabID;
            c.setQuery(query3,"");
            
            }
            
            JOptionPane.showMessageDialog(this,"Invoice Added");
        
        
            String total = subTotalTxt.getText().trim();
            String invid = invoicenoTxt.getText().trim();
            String paid = paidTxt.getText().trim();
            String query2 = "INSERT INTO invoice_payment(invoice_invoice_id, total )VALUES(" 
                + invid  + ","
                + total          
                + ")";
                int gen = c.setQuery(query2,"");

                if(cc==1){
                    String query3 = "INSERT INTO cheque (cheque_number, cheque_date,bank_name,invoice_payment_invoice_payment_id )VALUES(" 
                    + chequeid  + ","
                    + "'"+dates+ "'"+","  
                    + "'"+banks+ "'"+","
                    + + gen         
                    + ")";
                    c.setQuery(query3,"");

                }else if (cc==2){    
                    String query4 = "INSERT INTO credit_card (credit_card_no, card_type,invoice_payment_invoice_payment_id,bank )VALUES(" 
                    + "'"+ccardno+ "'"  + ","
                    + "'"+ccardtype+ "'"+ ","

                    + gen + ","   
                    + "'"+ cbank + "'"
                    + ")";
                    c.setQuery(query4,"");

                }else{
                    String query6 = "INSERT INTO cash_c(paid_amount,invoice_payment_invoice_payment_id )VALUES(" 
                        +  paid   + ","
                        +  gen       

                        + ")";
                        c.setQuery(query6,"");
                }
                
//            int id1 = Integer.parseInt(invoicenoTxt.getText());
//                
                    cusidTxt.setText("");
                    int in=Integer.parseInt(invoicenoTxt.getText().toString());
                    invoicenoTxt.setText(Integer.toString(in+1));          
                    netTotalTxt.setText(""+0.00);
                    NumberOfItemsTxt.setText(""+0);
                    discTotalTxt.setText(""+0.00);
                    subTotalTxt.setText(""+0.00);
                    paidTxt.setText(""+0.00);
                    balanceTxt.setText(""+0.00);
                    cusNameTxt.setText("");
                    dtm.setRowCount(0);     
                    
            paidTxt.setEditable(true);
            paidTxt.setBackground(Color.WHITE);

            balanceTxt.setEditable(true);
            balanceTxt.setBackground(Color.WHITE);
            
//          Report r= new Report();
//          HashMap map = new HashMap();
//          map.put("Invoice_id",id1);
//          r.generateReport("Invoice1.jrxml", map);
        
        }
// TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void itemIDTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemIDTxtMouseClicked
        ItemViwe a = new ItemViwe(this);
        a.setVisible(true);
        getParent().add(a);
        a.toFront();
       
        
    }//GEN-LAST:event_itemIDTxtMouseClicked

    private void itemIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIDTxtActionPerformed
    }//GEN-LAST:event_itemIDTxtActionPerformed

    private void netTotalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netTotalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netTotalTxtActionPerformed

    private void subTotalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTotalTxtActionPerformed

    private void NumberOfItemsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfItemsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfItemsTxtActionPerformed

    private void discTotalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discTotalTxtActionPerformed
          
        // TODO add your handling code here:
    }//GEN-LAST:event_discTotalTxtActionPerformed

    private void barTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barTxtActionPerformed

        Connect c = new Connect(); 
        String query = "SELECT  item_code, item_barcode, item_name FROM item WHERE item_barcode like '%"+barTxt.getText()+"%'" ;
        ResultSet reset = c.getQuery(query);
        
        try {
            while(reset.next()){
                int itmno = reset.getInt("item_code");
                int barcode = reset.getInt("item_barcode");
                String itmname = reset.getString("item_name");
                
                
                itemIDTxt.setText(""+itmno);
                barTxt.setText(""+barcode);
                nameTxt.setText(itmname);
            
            }   
        } catch (SQLException ex) {
            Logger.getLogger(Invoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_barTxtActionPerformed

    private void itemIDTxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_itemIDTxtPropertyChange
      
    }//GEN-LAST:event_itemIDTxtPropertyChange

    private void empTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empTxtMouseClicked
        // TODO add your handling code here:
        EmployeeList em=new EmployeeList(this);
        em.setVisible(true);
        getParent().add(em);
        em.toFront();
    }//GEN-LAST:event_empTxtMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        paidTxt.setText("0.00");
        paidTxt.setEditable(false);
        paidTxt.setBackground(Color.gray);
        balanceTxt.setText("0.00");
        balanceTxt.setEditable(false);
        balanceTxt.setBackground(Color.gray);
        
        Cheque cq = new Cheque(this);
        cq.setVisible(true);
        getParent().add(cq);
        cq.toFront();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        paidTxt.setText("0.00");
        paidTxt.setEditable(false);
        paidTxt.setBackground(Color.gray);

        balanceTxt.setText("0.00");
        balanceTxt.setEditable(false);
        balanceTxt.setBackground(Color.gray);

        
        CreditCard p = new CreditCard(this);
        p.setVisible(true);
        getParent().add(p);
        p.toFront();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void paidTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidTxtFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_paidTxtFocusGained

    private void paidTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidTxtFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_paidTxtFocusLost

    private void qtyTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTxtFocusLost

    private void qtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTxtActionPerformed
    }//GEN-LAST:event_qtyTxtActionPerformed

    private void qtyTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTxtKeyPressed

        // TODO add your handling code here:
       
           
    }//GEN-LAST:event_qtyTxtKeyPressed

    private void qtyTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTxtKeyReleased
        // TODO add your handling code here:
        
        String unitp = unitpTxt.getText();
        String qty = qtyTxt.getText();
        
            if (qty.equals("")){ // if not this gives error of null string
            
            }else {
                double qtyD = Double.parseDouble(qty);// to get total
                double unitpD = Double.parseDouble(unitp);
                double totalText = (qtyD * unitpD);
                totalTxt.setText(""+totalText);
            }     
             
            if (evt.getKeyCode()== KeyEvent.VK_ENTER){ // to enter data to table
                String id = itemIDTxt.getText();
                String name = nameTxt.getText();
                String discount = discountTxt.getText();

                double qtyD = Double.parseDouble(qty);
                double unitpD = Double.parseDouble(unitp);
                double disD = Double.parseDouble(discount);
                double total = qtyD * unitpD;
                double finaltotal = (qtyD * unitpD)-(qtyD * disD);

        
                int i;
                boolean found = false;
                for (i = 0; i < invtable.getRowCount(); i++) {
                    String tabID = invtable.getValueAt(i, 0).toString();
                    if (id.equals(tabID)) {
                        found = true;
                        break;
                    }
                }
                if (found) {
                    double oldQty = Double.parseDouble(invtable.getValueAt(i, 2).toString());
                    double newQty = oldQty + qtyD;
                    invtable.setValueAt("" + newQty, i, 2);

                    double newTotal = (newQty * unitpD)-(newQty * disD);
                    invtable.setValueAt("" + newTotal, i, 4);

                } else {
                    dtm.addRow(new Object[]{id, name, qty, unitp, finaltotal, discount});
                }

                try {
                    double prevTotal = Double.parseDouble(netTotalTxt.getText());
                    netTotalTxt.setText("" + (prevTotal + total));
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null, "Total Filed is empty");
                }
                try {
                    double prevDiscount = Double.parseDouble(discTotalTxt.getText());
                    double disc = Double.parseDouble(discount);

                    double totaldisc = prevDiscount+ (disc*qtyD);

                    discTotalTxt.setText("" +  totaldisc);

                    String nettot = netTotalTxt.getText();
                    double netTot = Double.parseDouble(nettot);
                    double subTot = netTot-totaldisc;
                    subTotalTxt.setText(""+subTot);


                } catch (NumberFormatException nfe) {
                }
        
                itemIDTxt.setText("");
                nameTxt.setText("");
                qtyTxt.setText("");
                unitpTxt.setText("");
                totalTxt.setText("");
                discountTxt.setText(""+0.00);
                barTxt.setText("");
                
                barTxt.requestFocusInWindow();

                int itemNo = invtable.getRowCount();
                NumberOfItemsTxt.setText(""+itemNo);
                if(NumberOfItemsTxt.equals("0")){
                    JOptionPane.showMessageDialog(this,"Please Add Items");
                }

            }

       
    }//GEN-LAST:event_qtyTxtKeyReleased

    private void qtyTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTxtKeyTyped
        // TODO add your handling code here:
                
    }//GEN-LAST:event_qtyTxtKeyTyped

    private void paidTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidTxtKeyReleased
        // TODO add your handling code here:
        String subtot = subTotalTxt.getText();
        String paid = paidTxt.getText();

        double subTot = Double.parseDouble(subtot);
        double Paid = Double.parseDouble(paid);
        double balance = Paid - subTot;
        balanceTxt.setText(Double.toString(balance));
    }//GEN-LAST:event_paidTxtKeyReleased

    private void barTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barTxtKeyReleased
        // TODO add your handling code here:
        Connect c = new Connect(); 
        String query = "SELECT  item_code,  item_name FROM item WHERE item_barcode like '%"+barTxt.getText()+"%'" ;
        if (barTxt.getText().length()== 10){      
        ResultSet reset = c.getQuery(query);
        
        try {
            while(reset.next()){
                int itmno = reset.getInt("item_code");
                String itmname = reset.getString("item_name");
                
                
            itemIDTxt.setText(""+itmno);
            nameTxt.setText(itmname);
            
            }   } catch (SQLException ex) {
            Logger.getLogger(Invoice.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         if(barTxt.getText().length()==10){
                    qtyTxt.requestFocusInWindow();
                
        String query3 = "SELECT discount, retail_price FROM stock_has_item WHERE item_item_code = "+Integer.parseInt(itemIDTxt.getText())+"" ;
        
        ResultSet reset3 = c.getQuery(query3);
        
        try {
            while(reset3.next()){
            
            int dis = reset3.getInt("discount");
            int rpricee = reset3.getInt("retail_price");
            
            String disc = Integer.toString(dis);
            String rprice = Integer.toString(rpricee);

            unitpTxt.setText(rprice);
            discountTxt.setText(disc);
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItemViwe.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }
    }//GEN-LAST:event_barTxtKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void itemIDTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemIDTxtFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_itemIDTxtFocusGained

    private void nameTxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nameTxtPropertyChange
        // TODO add your handling code here:
                  

    }//GEN-LAST:event_nameTxtPropertyChange

    private void itemIDTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemIDTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIDTxtMouseEntered

    private void qtyTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTxtMouseClicked

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBtnActionPerformed
    void setItem(int itemno,String itemname,int barcode){

        int ino = itemno;
        int bcode = barcode;
        String iname = itemname;
        
        itemIDTxt.setText(""+ino);
        barTxt.setText(""+bcode);
        nameTxt.setText(iname);
        
        Connect c = new Connect();
        
        String query3 = "SELECT discount, retail_price FROM stock_has_item WHERE item_item_code like '%"+ino+"%'" ;
        ResultSet reset3 = c.getQuery(query3);
        
        try {
            while(reset3.next()){
            
            int dis = reset3.getInt("discount");
            int rpricee = reset3.getInt("retail_price");
            
            String disc = Integer.toString(dis);
            String rprice = Integer.toString(rpricee);

            unitpTxt.setText(rprice);
            discountTxt.setText(disc);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItemViwe.class.getName()).log(Level.SEVERE, null, ex);
        }
                 qtyTxt.requestFocusInWindow();

// TODO add your handling code here:
    }   
    
    void SetEmployee(int id,String name){
        int idd = id;
        String ename=name;
        empTxt.setText(""+idd);
        cashNameTxt.setText(ename);
    }
    
    public void SetCheque(String bank, int cno, String cdate){
        banks = bank;
        chequeid = cno;
        dates = cdate;
        cc=1;
    }
    
    public void SetCreditCardValue(String card, String no,String ccbank){
        ccardtype = card;
        ccardno= no;
        cbank = ccbank;
        cc=2;
    }
    
    void Invoiceno(){
        Connect c = new Connect();
        
        String query3 = "SELECT invoice_id FROM invoice ORDER BY invoice_id DESC LIMIT 1" ;
        ResultSet reset3 = c.getQuery(query3);
        
        try {
            while(reset3.next()){
            
            int id = reset3.getInt("invoice_id");
            
            String ids= Integer.toString((id+1));
            invoicenoTxt.setText(ids);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Invoice.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
    
     void setCustomer (int cusno, String name){
        int cno = cusno;
        String cname = name;
        cusidTxt.setText(""+cno);
        cusNameTxt.setText(cname);
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumberOfItemsTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField balanceTxt;
    private javax.swing.JTextField barTxt;
    private javax.swing.JTextField cashNameTxt;
    private javax.swing.JButton clearTxt;
    private javax.swing.JTextField cusNameTxt;
    private javax.swing.JTextField cusidTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField discTotalTxt;
    private javax.swing.JTextField discountTxt;
    private javax.swing.JTextField empTxt;
    private javax.swing.JTextField invoicenoTxt;
    private javax.swing.JTable invtable;
    private javax.swing.JTextField itemIDTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField netTotalTxt;
    private javax.swing.JTextField paidTxt;
    private javax.swing.JTextField qtyTxt;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField subTotalTxt;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JTextField unitpTxt;
    // End of variables declaration//GEN-END:variables
}
