/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.Connect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasini
 */
public class ItemViwe extends javax.swing.JInternalFrame {

    /**
     * Creates new form ItemViwe1
     */
    DefaultTableModel dtm;
    
    public ItemViwe() {
        initComponents();
                dtm = (DefaultTableModel) itemTbl.getModel();
                getValues();

    }
    
    Invoice iobj;

    ItemViwe(Invoice obj) {
        initComponents();
        dtm = (DefaultTableModel) itemTbl.getModel();
        getValues();
        iobj = obj;
        
    }
    
    PurchaseRteurnNote npo;

    ItemViwe(PurchaseRteurnNote npon) {
        initComponents();
        dtm = (DefaultTableModel) itemTbl.getModel();
        getValues();
        npo = npon;
        
    }
    
    PurchaseOrder po;

    ItemViwe(PurchaseOrder poo) {
        initComponents();
        dtm = (DefaultTableModel) itemTbl.getModel();
        getValues();
        po = poo;
        
    }
    
    Grn gobj;
    ItemViwe(Grn obj) {
        initComponents();
        dtm = (DefaultTableModel) itemTbl.getModel();
        getValues();
        gobj = obj;
    }
    
    SalesReturn srobj;
    ItemViwe(SalesReturn obj) {
        initComponents();
        dtm = (DefaultTableModel) itemTbl.getModel();
        getValues();
        srobj = obj;
    }
    
//    EditItem eiobj;
//    ItemViwe(EditItem obj){
//        initComponents();
//        dtm = (DefaultTableModel) itemTbl.getModel();
//        getValues();
//        eiobj = obj;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        itemTbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item no", "Item Name", "Bar code", "Catogory no", "descriptionl", "supplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemTbl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 810, 413));

        jPanel3.setBackground(new java.awt.Color(17, 153, 148));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Search By Name");

        searchTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Remove");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 830, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTblMouseClicked
        if (evt.getClickCount() == 2) {
            try{
                int row = itemTbl.getSelectedRow();
                
                int itemno = (int) itemTbl.getValueAt(row, 0);
                String itemname = itemTbl.getValueAt(row, 1).toString();
                int barcode = (int) itemTbl.getValueAt(row, 2);
              
                

                if (iobj!=null) {
                    iobj.setItem(itemno, itemname,barcode);
                }
                if (npo!=null) {
                    npo.setItem(itemno, itemname,barcode);
                }
                if (po!=null) {
                    po.setItem(itemno, itemname);
                }
               if (gobj!=null) {
                   gobj.setItem(itemno,  itemname);
                }
               if (srobj!=null) {
                   srobj.setItem(itemno,  itemname);
                }
    //           if (eiobj!=null) {
    //               eiobj.setItem2(catno, itemno, barcode, itemname, reoder, qty, costprice, salesprice);
    //            }            
        
                this.dispose();
            }catch (Exception ex) {
                ex.printStackTrace();
            }
            
        }

             // TODO add your handling code here:
    }//GEN-LAST:event_itemTblMouseClicked

    private void searchTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyPressed
       

        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtKeyPressed

    private void searchTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyTyped
           // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        NewItem a =new NewItem();
//        FirstDisplay.display.add(a);
//        a.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        // TODO add your handling code here:
        Connect c = new Connect();
        
        String query = "SELECT item_catogory_item_catogory_id, item_code, item_barcode, item_name, item_description FROM item" 
                + " WHERE item_name like '%"+searchTxt.getText()+"%'" ;
        ResultSet reset = c.getQuery(query);
        dtm.setRowCount(0);
        try {
            while(reset.next()){
            int catno = reset.getInt("item_catogory_item_catogory_id");
            int itmno = reset.getInt("item_code");
            int barcode = reset.getInt("item_barcode");
            String itmname = reset.getString("item_name");
            String des = reset.getString("item_description");
            
            dtm.addRow(new Object[]{ itmno,itmname, barcode, catno, des });
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItemViwe.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_searchTxtKeyReleased
    public void getValues(){
    
        Connect c = new Connect(); 
        String query = "SELECT item_catogory_item_catogory_id, item_code, item_barcode, item_name, item_description FROM item" ;
        ResultSet reset = c.getQuery(query);
        try {
            while(reset.next()){
            int catno = reset.getInt("item_catogory_item_catogory_id");
            int itmno = reset.getInt("item_code");
            int barcode = reset.getInt("item_barcode");
            String itmname = reset.getString("item_name");
            String des = reset.getString("item_description");
            
            dtm.addRow(new Object[]{ itmno,itmname, barcode, catno, des });
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItemViwe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable itemTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
