package interfaces;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import database.Connect;
import report.Report;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasini
 */
public class SupplierList extends javax.swing.JInternalFrame {

    /**
     * Creates new form SupplierViwe1
     */
    DefaultTableModel dtm;
    
    public SupplierList() {
        initComponents();
        dtm = (DefaultTableModel) supTbl.getModel();
                getValues();
    }
    
    
    PurchaseOrder po;
    public SupplierList(PurchaseOrder poobj) {
        initComponents();
        dtm = (DefaultTableModel) supTbl.getModel();
                getValues();
                po=poobj;
    }
    
    SalesReturn sr;
    public SupplierList(SalesReturn srobj) {
        initComponents();
        dtm = (DefaultTableModel) supTbl.getModel();
                getValues();
                sr=srobj;
    }
    Grn gobj;
    SupplierList(Grn obj){
    initComponents();
            dtm = (DefaultTableModel) supTbl.getModel();
            getValues();
            gobj = obj;

}
//    EditSupplier esobj;
//
//    SupplierViwe(EditSupplier obj){
//    initComponents();
//    dtm = (DefaultTableModel) supTbl.getModel();
//    getValues();
//    esobj = obj;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        refreahBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        supTbl = new javax.swing.JTable();
        printBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        refreahBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refreahBtn.setText("Refresh");
        refreahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreahBtnActionPerformed(evt);
            }
        });

        supTbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        supTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Company Name", "Address", "Company Phone", "Company E-Mail", "Agent Name", "Agent Name", "Agent Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supTbl);

        printBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        printBtn.setText("Print Report");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Search By Name");

        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(refreahBtn)
                    .addComponent(printBtn)
                    .addComponent(jLabel1)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        jPanel3.setBackground(new java.awt.Color(17, 153, 148));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("New Supplier");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("*  To edit a supplier double click on respective row");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreahBtnActionPerformed
        // TODO add your handling code here:
        Connect c = new Connect(); 
        String query = "SELECT supplier_id,supplier_name, sup_add, sup_phn, sup_mail, agnt_name,  agnt_phn, agnt_mail  FROM supplier"  ;
        ResultSet reset = c.getQuery(query);
        dtm.setRowCount(0);
        try {
            while(reset.next()){
                int id = reset.getInt("supplier_id");
                String cname = reset.getString("supplier_name");
                 String cadd = reset.getString("sup_add");
                String cphn = reset.getString("sup_phn");
                String cmail = reset.getString("sup_mail");
                String aname = reset.getString("agnt_name");
                String aphn = reset.getString("agnt_phn");
                String amail = reset.getString("agnt_mail");


                
                dtm.addRow(new Object[]{id, cname, cadd, cphn,cmail, aname,aphn ,amail});
            }
        } catch (SQLException ex) {
            Logger.getLogger(SupplierList.class.getName()).log(Level.SEVERE, null, ex);
        }
        searchTxt.setText("");
    }//GEN-LAST:event_refreahBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        AddNewSupplier a = new AddNewSupplier();
        a.setVisible(true);    
        getParent().add(a);
        a.toFront();
//         TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        Report r= new Report();        
        HashMap map = new HashMap();
        r.generateReport("Supplier List.jrxml", map);        
    // TODO add your handling code here:
    }//GEN-LAST:event_printBtnActionPerformed

    private void supTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supTblMouseClicked
        if (evt.getClickCount() == 2) {
            int row = supTbl.getSelectedRow();
            int supid = (int) supTbl.getValueAt(row, 0);
            String supname = supTbl.getValueAt(row, 1).toString();
            String address = supTbl.getValueAt(row, 2).toString();
            String companyphn = supTbl.getValueAt(row, 3).toString();
            String smail = supTbl.getValueAt(row, 4).toString();
            String agentname = supTbl.getValueAt(row, 5).toString();
            String agentphn = supTbl.getValueAt(row, 6).toString();

            String amail = supTbl.getValueAt(row, 7).toString();

            
            if(po != null){
            po.setSupplier(supid,supname);
                        this.dispose();

            }
            else if(sr != null){
            sr.setSupplier(supid,supname);
                        this.dispose();

            }
            else if(gobj != null){
            gobj.setSupplier(supid,supname);
                        this.dispose();

            }else{
                EditSupplier es= new EditSupplier();
                es.setVisible(true);
                getParent().add(es);
                es.toFront();
            es.setinfo(supid, supname,address, companyphn,smail, agentname,  agentphn, amail );
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_supTblMouseClicked

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    private void searchTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyTyped
           // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtKeyTyped

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        // TODO add your handling code here:
        Connect c = new Connect(); 
        String query = "SELECT supplier_id,supplier_name, sup_add, sup_phn, sup_mail, agnt_name,  agnt_phn, agnt_mail  "
                + "FROM supplier WHERE supplier_name like '%"+searchTxt.getText()+"%'"  ;

        ResultSet reset = c.getQuery(query);
        dtm.setRowCount(0);
        try {
            while(reset.next()){
               int id = reset.getInt("supplier_id");
                String cname = reset.getString("supplier_name");
                 String cadd = reset.getString("sup_add");
                String cphn = reset.getString("sup_phn");
                String cmail = reset.getString("sup_mail");
                String aname = reset.getString("agnt_name");
                String aphn = reset.getString("agnt_phn");
                String amail = reset.getString("agnt_mail");
                
                dtm.addRow(new Object[]{id, cname, cadd, cphn,cmail, aname,aphn ,amail});
            }
        } catch (SQLException ex) {
            Logger.getLogger(SupplierList.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_searchTxtKeyReleased
public void getValues(){
    
        Connect c = new Connect(); 
        String query = "SELECT supplier_id,supplier_name, sup_add, sup_phn, sup_mail, agnt_name,  agnt_phn, agnt_mail  FROM supplier"  ;
        ResultSet reset = c.getQuery(query);
        try {
            while(reset.next()){
                int id = reset.getInt("supplier_id");
                String cname = reset.getString("supplier_name");
                 String cadd = reset.getString("sup_add");
                String cphn = reset.getString("sup_phn");
                String cmail = reset.getString("sup_mail");
                String aname = reset.getString("agnt_name");
                String aphn = reset.getString("agnt_phn");
                String amail = reset.getString("agnt_mail");


                
                dtm.addRow(new Object[]{id, cname, cadd, cphn,cmail, aname,aphn ,amail});
            }
        } catch (SQLException ex) {
            Logger.getLogger(SupplierList.class.getName()).log(Level.SEVERE, null, ex);
        }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton refreahBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable supTbl;
    // End of variables declaration//GEN-END:variables
}
